# Documentation at https://goreleaser.com
brews:
  - tap:
      owner: laurenzlong
      name: homebrew-cli
    folder: Formula
    description: The Ampersand CLI
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    binary: amp
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X github.com/amp-labs/cli/vars.CommitID={{.FullCommit}}
      - -X github.com/amp-labs/cli/vars.Branch={{.Branch}}
      - -X github.com/amp-labs/cli/vars.Stage=prod
      - -X github.com/amp-labs/cli/vars.BuildDate={{.Now}}
      - -X github.com/amp-labs/cli/vars.Version={{.Version}}
      - -X github.com/amp-labs/cli/vars.ClerkRootURL=https://clerk.withampersand.com/
      - -X github.com/amp-labs/cli/vars.LoginURL=https://ampersand-cli-auth-prod.web.app
      - -X github.com/amp-labs/cli/vars.GCSBucket=ampersand-prod-deploy-uploads
      - -X github.com/amp-labs/cli/vars.GCSKey=AIzaSyDGWb5ncKSvkeNl5ZO_zVnP_5KdiKjo-i4
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
