version: "3"

tasks:
    do_build:
        desc: Build the CLI (don't call directly)
        cmds:
            - go generate ./...
            - CGO_ENABLED=0 go build -ldflags="-X {{.PKG}}.CommitID={{.GIT_COMMIT}} -X {{.PKG}}.Branch={{.GIT_BRANCH}} -X {{.PKG}}.Stage={{.STAGE}} -X '{{.PKG}}.BuildDate={{.BUILD_DATE}}' -X {{.PKG}}.Version={{.VERSION}} -X {{.PKG}}.ClerkRootURL={{.CLERK_URL}} -X {{.PKG}}.LoginURL={{.LOGIN_URL}} -X {{.PKG}}.ApiURL={{.API_URL}}" -o bin/amp{{if eq OS "windows"}}.exe{{end}} main.go
        vars:
            GIT_COMMIT:
                sh: git log -n 1 --format=%H
            GIT_BRANCH:
                sh: git rev-parse --abbrev-ref HEAD
            BUILD_DATE:
                sh: date -u '+%Y-%m-%d %I:%M%p'
            VERSION:
                sh: git tag --points-at HEAD | sed 's/^v//'
            PKG: github.com/amp-labs/cli/vars

    build-local:
        desc: Build a CLI configured for the local stage
        cmds:
            - task: do_build
              vars:
                  CLERK_URL: https://welcomed-snapper-45.clerk.accounts.dev
                  LOGIN_URL: https://ampersand-cli-auth-dev.web.app
                  API_URL: http://127.0.0.1:8080
                  GCS_BUCKET: ampersand-dev-deploy-uploads
                  GCS_KEY: "AIzaSyBvOQ41f7igI0wtclU0JgqBKfPtOluyjpg"
                  STAGE: local

    build-dev:
        desc: Build a CLI configured for the dev stage
        cmds:
            - task: do_build
              vars:
                  CLERK_URL: https://welcomed-snapper-45.clerk.accounts.dev
                  LOGIN_URL: https://ampersand-cli-auth-dev.web.app
                  API_URL: https://dev-api.withampersand.com
                  STAGE: dev

    build-staging:
        desc: Build a CLI configured for the staging stage
        cmds:
            - task: do_build
              vars:
                  CLERK_URL: https://welcomed-snapper-45.clerk.accounts.dev
                  LOGIN_URL: https://ampersand-cli-auth-stag.web.app
                  API_URL: https://staging-api.withampersand.com
                  STAGE: staging

    build-prod:
        desc: Build a CLI configured for the prod stage
        cmds:
            - task: do_build
              vars:
                  CLERK_URL: https://clerk.withampersand.com
                  LOGIN_URL: https://cli-signin.withampersand.com
                  API_URL: https://api.withampersand.com
                  STAGE: prod

    build:
        desc: An alias for build-dev
        cmds:
            - task: build-dev

    lint:
        desc: Run the linter
        cmds:
            - golangci-lint run -c .golangci.yml

    fix:
        desc: Fix lint errors
        cmds:
            - wsl --allow-cuddle-declarations --fix ./...
            - gci write .
            - golangci-lint run -c .golangci.yml --fix
