version: "3"

tasks:
    build:
        desc: Build the CLI
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/amp{{if eq OS "windows"}}.exe{{end}} main.go 

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/amp main.go 
