// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for InputValidationIssueIn.
const (
	Body   InputValidationIssueIn = "body"
	Header InputValidationIssueIn = "header"
	Path   InputValidationIssueIn = "path"
	Query  InputValidationIssueIn = "query"
)

// Valid indicates whether the value is a known member of the InputValidationIssueIn enum.
func (e InputValidationIssueIn) Valid() bool {
	switch e {
	case Body:
		return true
	case Header:
		return true
	case Path:
		return true
	case Query:
		return true
	default:
		return false
	}
}

// ApiProblem defines model for ApiProblem.
type ApiProblem struct {
	// Causes A list of problems that caused this problem. This can be used to represent multiple
	// root causes. There is no guaranteed ordering of the causes.
	//
	//
	// Example: ["database connection failed","database query failed","unable to fetch user"]
	Causes *[]string `json:"causes,omitempty"`

	// Context Additional context for the problem
	//
	// Example: {"name":"Rick Sanchez"}
	Context *map[string]interface{} `json:"context,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`

	// Href An absolute URI that, when dereferenced, provides human-readable documentation for the problem type (e.g. using HTML).
	Href *string `json:"href,omitempty"`

	// Instance An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
	Instance *string `json:"instance,omitempty"`

	// Remedy A brief description of how to resolve the problem
	//
	// Example: Shorten your input to be under 100 characters
	Remedy *string `json:"remedy,omitempty"`

	// RequestId A unique identifier for the request, useful for debugging
	//
	// Example: 89eb1ffb-2a54-4105-aaae-7bf990f1aa69#87715
	RequestId *string `json:"requestId,omitempty"`

	// RetryAfter A timestamp after which the request can be retried, formatted as RFC-3339
	//
	// Example: 2024-04-22T18:55:28.456076Z
	RetryAfter *time.Time `json:"retryAfter,omitempty"`

	// Retryable Whether the request can be retried
	//
	// Example: false
	Retryable *bool `json:"retryable,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	//
	// Example: 503
	Status *int32 `json:"status,omitempty"`

	// Subsystem The subsystem that generated the problem
	//
	// Example: api
	Subsystem *string `json:"subsystem,omitempty"`

	// SupportEmail An email address to contact for support
	//
	// Example: support@withampersand.com
	SupportEmail *openapi_types.Email `json:"supportEmail,omitempty"`

	// SupportPhone A phone number to contact for support
	//
	// Example: +1-555-555-5555
	SupportPhone *string `json:"supportPhone,omitempty"`

	// SupportUrl A URL to contact for support
	//
	// Example: https://withampersand.com/support
	SupportUrl *string `json:"supportUrl,omitempty"`

	// Time The time the problem occurred, formatted as RFC-3339
	//
	// Example: 2024-04-22T18:55:28.456076Z
	Time *time.Time `json:"time,omitempty"`

	// Title A short summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized).
	//
	// Example: Service Unavailable
	Title *string `json:"title,omitempty"`

	// Type An absolute URI that identifies the problem type
	Type *string `json:"type,omitempty"`
}

// InputValidationIssue An issue detected during input validation.
type InputValidationIssue struct {
	// Detail A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`

	// Href An absolute URI that, when dereferenced, provides human-readable documentation for the problem type (e.g. using HTML).
	Href *string `json:"href,omitempty"`

	// In The location of the invalid input
	In *InputValidationIssueIn `json:"in,omitempty"`

	// Instance An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
	Instance *string `json:"instance,omitempty"`

	// Name The name of the invalid input
	Name *string `json:"name,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	//
	// Example: 503
	Status *int32 `json:"status,omitempty"`

	// Title A short summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized).
	//
	// Example: Service Unavailable
	Title *string `json:"title,omitempty"`

	// Type An absolute URI that identifies the problem type
	Type *string `json:"type,omitempty"`

	// Value The value of the erroneous input
	Value interface{} `json:"value,omitempty"`
}

// InputValidationIssueIn The location of the invalid input
type InputValidationIssueIn string

// InputValidationProblem defines model for InputValidationProblem.
type InputValidationProblem struct {
	// Detail A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`

	// Href An absolute URI that, when dereferenced, provides human-readable documentation for the problem type (e.g. using HTML).
	Href *string `json:"href,omitempty"`

	// Instance An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
	Instance *string                 `json:"instance,omitempty"`
	Issues   *[]InputValidationIssue `json:"issues,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	//
	// Example: 503
	Status *int32 `json:"status,omitempty"`

	// Title A short summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized).
	//
	// Example: Service Unavailable
	Title *string `json:"title,omitempty"`

	// Type An absolute URI that identifies the problem type
	Type *string `json:"type,omitempty"`
}

// Problem A Problem Details object (RFC 9457).
//
// Additional properties specific to the problem type may be present.
//
// Example: {"detail":"Description of specific occurrence of the problem","href":"https://www.belgif.be/specification/rest/api-guide/#standardized-problem-types","instance":"urn:uuid:123e4567-e89b-12d3-a456-426614174000","status":400,"title":"Description of the type of problem that occurred","type":"urn:problem-type:exampleOrganization:exampleProblem"}
type Problem struct {
	// Detail A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail,omitempty"`

	// Href An absolute URI that, when dereferenced, provides human-readable documentation for the problem type (e.g. using HTML).
	Href *string `json:"href,omitempty"`

	// Instance An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	//
	// Example: 503
	Status *int32 `json:"status,omitempty"`

	// Title A short summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized).
	//
	// Example: Service Unavailable
	Title *string `json:"title,omitempty"`

	// Type An absolute URI that identifies the problem type
	Type *string `json:"type,omitempty"`
}

// InputValidationProblemResponse Example: {"detail":"The input message is incorrect","instance":"123456-1234-1235-4567489798","issues":[{"detail":"exampleNumericProperty should be numeric","in":"path","name":"exampleNumericProperty","type":"about:blank","value":"abc"},{"detail":"examplePropertyWithPattern a2345678901 doesn't match pattern '^\\d{11}$'","in":"body","name":"items[0].examplePropertyWithPattern","title":"Input isn't valid with respect to schema","type":"about:blank","value":"a2345678901"}],"status":400,"title":"Bad Request","type":"about:blank"}
type InputValidationProblemResponse = InputValidationProblem

// ProblemResponse A Problem Details object (RFC 9457).
//
// Additional properties specific to the problem type may be present.
//
// Example: {"detail":"Description of specific occurrence of the problem","href":"https://www.belgif.be/specification/rest/api-guide/#standardized-problem-types","instance":"urn:uuid:123e4567-e89b-12d3-a456-426614174000","status":400,"title":"Description of the type of problem that occurred","type":"urn:problem-type:exampleOrganization:exampleProblem"}
type ProblemResponse = Problem
