# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "The Ampersand CLI"
  homepage ""
  version "0.0.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/amp-labs/cli/releases/download/v0.0.9/cli_Darwin_arm64.tar.gz"
      sha256 "5426c69f1cf1c8c0dcc34be7d0e43c38d2d1514edd4cf3972ad926f9a4bb4c98"

      def install
        bin.install "amp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/amp-labs/cli/releases/download/v0.0.9/cli_Darwin_x86_64.tar.gz"
      sha256 "526d4cd33fb6bace1768af2d8ce4dc66ebaf36086fc4c58f7994797aaf16fce7"

      def install
        bin.install "amp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amp-labs/cli/releases/download/v0.0.9/cli_Linux_arm64.tar.gz"
      sha256 "c41af339708512b33f076dc843641205c291ccc93186b4361c71dec2bfde79cb"

      def install
        bin.install "amp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/amp-labs/cli/releases/download/v0.0.9/cli_Linux_x86_64.tar.gz"
      sha256 "ce2bb137019066e293fe3b7d0c35ba799b22c376e08fad2d68415897de7cdd2b"

      def install
        bin.install "amp"
      end
    end
  end
end
