name: Build and test
run-name: ${{ github.actor }} is running go build / go test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.4"
          cache: false

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
