name: Build and test
run-name: ${{ github.actor }} is running go build / go test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.4"
          cache: false

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          dir: 'www'
          cmd: install # will run `yarn install` command

      - name: Generate
        run: go generate ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
