name: Linter
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Generate go code
        run: go generate ./...

      - name: Lint Go code
        uses: golangci/golangci-lint-action@v6
        with:
          skip-cache: true
          version: v1.64.3
