name: Linter
run-name: ${{ github.actor }} is running the linter
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        continue-on-error: false
        with:
          version: v2.9.0
